spring:
  application:
    name: base-domains
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    # Сортирует методы по алфавиту (GET, POST...)
    operationsSorter: method
    # Группирует эндпоинты по тегам
    tagsSorter: alpha
  # Позволяет сканировать только ваши пакеты (ускоряет запуск)
  packages-to-scan: net.javamicros.orderservice.controller