spring:
  kafka:
    bootstrap-servers: localhost:9092

    topic:
      name: order_topics

    listener:
      ack-mode: manual

    consumer:
      group-id: stock
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        spring.json.trusted.packages: "net.javamicros.basedomains.dto"
        spring.json.value.default.type: "net.javamicros.basedomains.dto.OrderEventModel"
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true
      enable-auto-commit: false
